### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "idUser": 1,
  "idRole": 1,
  "documentType": "CC",
  "identification": "89989888",
  "email": "jfelipe@gmail.com",
  "password": "jFelipe14"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jfelipe@gmail.com",
  "password": "jFelipe14"
}