### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "idUser": 1,
  "idRole": 1,
  "documentType": "CC",
  "identification": "899898",
  "email": "juan@gmail.com",
  "password": "Juan14"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "juan@gmail.com",
  "password": "Juan14"
}