### Recuperar todo
GET http://localhost:3000/services

### Recuperar un dato por id
GET http://localhost:3000/services/1


### Crear un dato con POST
POST http://localhost:3000/services
Content-Type: application/json

{
  "id_service": 1,
  "id_categoryService": 1,
  "name": "Bus",
  "price": 100,
  "state": "Activo"
}


### Borrar un dato
DELETE http://localhost:3000/services/1

### Actualizar un dato
PATCH http://localhost:3000/services/1
Content-Type: application/json

{
  "status": true
}